; Listing generated by Microsoft (R) Optimizing Compiler Version 19.15.26726.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\EmreAsus\AppData\Local\Temp\.NETFramework,Version=v4.6.1.AssemblyAttributes.cpp"
